<?php

class CoursesTableSeeder extends Seeder {

    public function run()
    {
        $courses = array(
            array("course_name" => "Computer Science", "university" => "University of Nairobi"),
            array("course_name" => "Industrial Design", "university" => "Sheffield, University of"),
            array("course_name" => "Digital Forensics", "university" => "Deakin University"),
            array("course_name" => "Psychology", "university" => "University of Michigan"),
            array("course_name" => "Health Science", "university" => "University of Science and Technology Beijing"),
            array("course_name" => "Engineering", "university" => "Middlebury College"),
            array("course_name" => "Social Care", "university" => "Elmhurst College"),
            array("course_name" => "Maths", "university" => "Griffith University"),
            array("course_name" => "English Literature", "university" => "Sauder School of Business"),
            array("course_name" => "English Language", "university" => "University of Southern Maine"),
            array("course_name" => "Business", "university" => "Nanyang Academy of Fine Arts"),
            array("course_name" => "Law", "university" => "Aalto University"),
            array("course_name" => "European Law", "university" => "Jonkoping University College"),
            array("course_name" => "Business Information Systems", "university" => "Florida International University"),
            array("course_name" => "Software Engineering", "university" => "Lebanese American University"),
            array("course_name" => "Product Design", "university" => "Imperial College London"),
            array("course_name" => "Computing", "university" => "Jiangxi University of Finance and Economics"),
            array("course_name" => "Advertising", "university" => "Regensburg University"),
            array("course_name" => "Banking - Commercial", "university" => "New York University"),
            array("course_name" => "Art", "university" => "Ealing & West London College"),
            array("course_name" => "Banking - Investment", "university" => "University of Witten/Herdecke"),
            array("course_name" => "Auditing/Tax", "university" => "Hankuk University of Foreign Studies"),
            array("course_name" => "E-Business", "university" => "Warburg Institute"),
            array("course_name" => "Arts/Entertainment/Media", "university" => "Liverpool John Moores University"),
            array("course_name" => "Automotive", "university" => "Erasmus University Rotterdam"),
            array("course_name" => "Accountancy", "university" => "University of South Australia"),
            array("course_name" => "Design", "university" => "University of Groningen"),
            array("course_name" => "Msc Construction Project Management", "university" => "Drake University"),
            array("course_name" => "Music", "university" => "University of Szeged"),
            array("course_name" => "Business Management", "university" => "Southampton, University of"),
            array("course_name" => "Politics And Eastern European Studies With A Year Abroad", "university" => "Abingdon and Witney College"),
            array("course_name" => "Politics And English", "university" => "University of Tsukuba"),
            array("course_name" => "International Politics", "university" => "Newcastle University"),
            array("course_name" => "IMML German", "university" => "Aalborg University"),
            array("course_name" => "BA Modern Languages With Business Management", "university" => "Chungang University"),
            array("course_name" => "BEng Mechanical Engineering", "university" => "Padjadjaran University"),
            array("course_name" => "Business And Management", "university" => "PACE University"),
            array("course_name" => "Business And Management (Accounting)", "university" => "Humboldt University"),
            array("course_name" => "History", "university" => "Chulalongkorn University"),
            array("course_name" => "Geography", "university" => "University of the Philippines - Los Banos"),
            array("course_name" => "PPS", "university" => "Sacred Heart University"),
            array("course_name" => "Environment, Society And Development", "university" => "Lodz University"),
            array("course_name" => "Sport Exercise Science", "university" => "National Sun Yat-sen University"),
            array("course_name" => "Forensic Science", "university" => "Morehouse College"),
            array("course_name" => "Criminology And Social Policy", "university" => "Dublin City University"),
            array("course_name" => "Commerce", "university" => "Columbia Business School"),
            array("course_name" => "Bar Professional Training Course", "university" => "Ecole Centrale de Paris"),
            array("course_name" => "BPTC", "university" => "University of Maine"),
            array("course_name" => "Creative Writing", "university" => "Kasetsart University"),
            array("course_name" => "Forensic Science With Crimonology", "university" => "Glasgow School of Art"),
            array("course_name" => "Ll.b Law With Criminology", "university" => "Molloy College"),
            array("course_name" => "Global Crime, Justice, Security", "university" => "Swiss School of International Banking"),
            array("course_name" => "Linguistics", "university" => "Cooper Union"),
            array("course_name" => "LLB LAW", "university" => "Obafemi Awololo University"),
            array("course_name" => "History And Politics", "university" => "Turku University"),
            array("course_name" => "LLB", "university" => "Management Development Institute"),
            array("course_name" => "BA, Hons Accounting And Finance", "university" => "Ochanomizu Univ"),
            array("course_name" => "Accountancy & Business Law", "university" => "Winthrop University"),
            array("course_name" => "Human Resource Management", "university" => "ENSAE"),
            array("course_name" => "Accounting And Financial Management", "university" => "University of Waterloo"),
            array("course_name" => "Biomedical Science", "university" => "ESSEC Business School (Paris)"),
            array("course_name" => "French And History", "university" => "Graduate University of Chinese Academy of Sciences"),
            array("course_name" => "BBA Management", "university" => "Barnet College"),
            array("course_name" => "German And Management", "university" => "Ecole Nationale Superieure de Techniques Avancees"),
            array("course_name" => "Biological Sciences", "university" => "University of KwaZulu Natal"),
            array("course_name" => "Law LLB", "university" => "The Grimsby Institute of Further & Higher Education"),
            array("course_name" => "History (BA Hons)", "university" => "Flinders University"),
            array("course_name" => "Economic And Social History", "university" => "Universidad Internacional"),
            array("course_name" => "Process Design Engineering", "university" => "Villanova University"),
            array("course_name" => "LPC", "university" => "Universidad Adolfo Ibanez (Creo que es Chilena tambien)"),
            array("course_name" => "Medicine", "university" => "University of St. La Salle - Bacolod"),
            array("course_name" => "Human Resource Management And Organisational Analysis", "university" => "Universita degli Studi di Venezia"),
            array("course_name" => "BA", "university" => "University of Bonn"),
            array("course_name" => "MBA", "university" => "SUNY Fredonia"),
            array("course_name" => "BSc Economics", "university" => "Universidad Ramon Llull"),
            array("course_name" => "Economics And Politics", "university" => "Universita Cattolica del Sacro Cuore"),
            array("course_name" => "Geography And Geology", "university" => "Delhi University"),
            array("course_name" => "MSc Digital Anthropology", "university" => "The State University of New Jersey"),
            array("course_name" => "Neuroscience", "university" => "Hobart and William Smith"),
            array("course_name" => "International Relations", "university" => "Ealing & West London College"),
            array("course_name" => "LLM In International Business Law", "university" => "Institut Superieur des Affaires (ISA)"),
            array("course_name" => "Modern Languages", "university" => "University of Newcastle"),
            array("course_name" => "Politics", "university" => "American University of Kuwait"),
            array("course_name" => "Environmental Science", "university" => "Duisenberg School of Finance"),
            array("course_name" => "LLB Law With European Law", "university" => "Aberdeen, University of"),
            array("course_name" => "Mathematics", "university" => "Royal Academy of Music"),
            array("course_name" => "Natural Sciences", "university" => "DIW Berlin"),
            array("course_name" => "Law With Criminology", "university" => "Universidad Panamericana"),
            array("course_name" => "Open Degree", "university" => "Parahyangan University"),
            array("course_name" => "Bachelor Of Computer Science Engineering", "university" => "Malaysia University of Science and Technology"),
            array("course_name" => "Philosophy", "university" => "Bishop Grosseteste College"),
            array("course_name" => "PPE", "university" => "Scuola Normale Superiore (Pisa)"),
            array("course_name" => "Applied Accounting", "university" => "Friedrich Alexander University"),
            array("course_name" => "LAW AND INTERNATIONAL RELATIONS", "university" => "BPP"),
            array("course_name" => "Social Work", "university" => "LUISS (Libera Universita Internazionale degli Studi Sociali)"),
            array("course_name" => "HR", "university" => "National Tsing-Hua University"),
            array("course_name" => "Wildlife Conservation With Zoo Biology", "university" => "University of San Jose - Recoletos"),
            array("course_name" => "Chinese", "university" => "University of Connecticut"),
            array("course_name" => "Maths And Accounting", "university" => "Asia Pacific College"),
            array("course_name" => "Business And HR Management", "university" => "Miriam College"),
            array("course_name" => "Law And French", "university" => "University of Central Florida"),
            array("course_name" => "Business Analysis And Consulting", "university" => "Scuola Superiore S.Anna (Pisa)"),
            array("course_name" => "Health And Social Care", "university" => "UHI Millennium Institute"),
            array("course_name" => "Social. Science", "university" => "Moscow State Technical University"),
            array("course_name" => "International Commercial & Maritime Law", "university" => "Bandung Institute of Technology"),
            array("course_name" => "BSc Computer Networks", "university" => "Coastal Carolina University"),
            array("course_name" => "Historical Archaeology", "university" => "Shanghai Maritime University"),
            array("course_name" => "English Literature And Politics", "university" => "Creighton University"),
            array("course_name" => "Chemistry", "university" => "Universita degli Studi di Roma/La Sapienza"),
            array("course_name" => "Business/Management", "university" => "Queen Mary, University of London"),
            array("course_name" => "Other", "university" => "Wilmington College"),
            array("course_name" => "Biology", "university" => "UHI Millennium Institute"),
            array("course_name" => "Economics", "university" => "Molloy College"),
            array("course_name" => "Languages", "university" => "Camberwell College of Arts"),
            array("course_name" => "English", "university" => "University of Nurtingen"),
            array("course_name" => "Physics", "university" => "Indian Institute of Management, Indore"),
            array("course_name" => "Sciences", "university" => "Richmond School of Business"),
            array("course_name" => "Classics", "university" => "College of the Holy Cross"),
            array("course_name" => "Information Technology", "university" => "University of Washington"),
            array("course_name" => "Education/Teaching", "university" => "Sabhal Mor Ostaig"),
            array("course_name" => "Electronic And Electrical Engineering", "university" => "Universidad Francisco Gavidia"),
            array("course_name" => "Civil Engineering", "university" => "Universita degli Studi di Firenze"),
            array("course_name" => "Agriculture", "university" => "Moscow University of People's Friendship"),
            array("course_name" => "Management Consultancy", "university" => "Clark Atlanta University"),
            array("course_name" => "Human Resources", "university" => "University of the Philippines - Pampanga"),
            array("course_name" => "Financial Management", "university" => "University of Limerick"),
            array("course_name" => "Marketing", "university" => "Scarborough Campus, University of Hull"),
            array("course_name" => "Mathematics/Statistics", "university" => "Abertay, University of"),
            array("course_name" => "Chemical Engineering", "university" => "Universita degli Studi di Padova"),
            array("course_name" => "Banking/Finance", "university" => "Winchester, University of"),
            array("course_name" => "Sport/Sports Management", "university" => "Schiller University"),
            array("course_name" => "Business Analytics", "university" => "College of Staten Island - Macaulay Honors College"),
            array("course_name" => "Retail/Merchandising", "university" => "New York University"),
            array("course_name" => "Business Intelligence/Market Research", "university" => "St. Xavier's College"),
            array("course_name" => "Actuarial", "university" => "St. John's University"),
            array("course_name" => "Material And Mineral Engineering", "university" => "ESB-Reutlingen"),
            array("course_name" => "Computer And Systems Engineering", "university" => "City University of Hong Kong"),
            array("course_name" => "Legal/Law", "university" => "Moscow State Technical University"),
            array("course_name" => "Pharmaceutical", "university" => "US Military Acedemy"),
            array("course_name" => "Environmental", "university" => "Dundee College"),
            array("course_name" => "Science/Research", "university" => "Royal Veterinary College"),
            array("course_name" => "Food And Drink", "university" => "Universita Cattolica di Milano"),
            array("course_name" => "Mechanical Engineering", "university" => "Doncaster College"),
            array("course_name" => "Architecture", "university" => "Singapore Polytechnic"),
            array("course_name" => "Charity/Non Profit", "university" => "University of the Witwatersrand"),
            array("course_name" => "Aeronautical Engineering", "university" => "University of Western Ontario"),
            array("course_name" => "Medical/Health", "university" => "Chuo University"),
            array("course_name" => "Administration/Secretarial", "university" => "Le Moyne College"),
            array("course_name" => "Public Sector/Governmental", "university" => "European Business School (Oestrich-Winkel)"),
            array("course_name" => "Anthropology", "university" => "Lebanese American University"),
            array("course_name" => "Property/Real Estate", "university" => "Brooklyn College"),
            array("course_name" => "Banking - Retail", "university" => "Hebrew University"),
            array("course_name" => "Sociology", "university" => "University of Southern Maine"),
            array("course_name" => "Mathematical & Computer Sciences", "university" => "XLRI, Jamshedpur"),
            array("course_name" => "Business & Management", "university" => "East China Normal University"),
            array("course_name" => "Arts & Humanities", "university" => "RCN Institute"),
            array("course_name" => "Physical Earth & Biological Sciences", "university" => "University of Calgary"),
            array("course_name" => "Social Sciences Incl Human Geography", "university" => "European Business School"),
            array("course_name" => "Accountancy Banking & Finance", "university" => "University of Pennsylvania"),
            array("course_name" => "BA(Hons) Politics And Modern History", "university" => "Askham Bryan College"),
            array("course_name" => "Law LLB (Hons)", "university" => "University of Phoenix"),
            array("course_name" => "LL.B (Hons)", "university" => "Barking College"),
            array("course_name" => "LLB Law With Politics", "university" => "Blackburn College"),
            array("course_name" => "(BA) English Literature And American Studies", "university" => "Birmingham, University of"),
            array("course_name" => "Law With Politics LLB", "university" => "Mahidol University"),
            array("course_name" => "International Business, Finance & Economics", "university" => "La Trobe University"),
            array("course_name" => "MSc International Politics", "university" => "University of the Philippines - Diliman"),
            array("course_name" => "Business And Law", "university" => "ESCP Europe (London)"),
            array("course_name" => "European Studies (Politics, History, French, Italian)", "university" => "Xi'an Jiaotong university"),
            array("course_name" => "LLM Laws", "university" => "SKEMA Business School"),
            array("course_name" => "Business & Law", "university" => "Blackburn College"),
            array("course_name" => "LL.M", "university" => "University of Koln"),
            array("course_name" => "German And History", "university" => "Nottingham Trent University"),
            array("course_name" => "LLM In International Finance And Banking Law", "university" => "St Andrews, University of"),
            array("course_name" => "Comparative Literature", "university" => "Hunan University"),
            array("course_name" => "LLM", "university" => "Ghent University"),
            array("course_name" => "Master Of Law", "university" => "Arizona State University"),
            array("course_name" => "MSc Social Cognition", "university" => "XLRI, Jamshedpur"),
            array("course_name" => "English Law And German Law", "university" => "Stirling, University of"),
            array("course_name" => "English Law & Hong Kong Law", "university" => "Edinburgh, University of"),
            array("course_name" => "LLB 2014", "university" => "Edinburgh, University of"),
            array("course_name" => "Law LLB 2015", "university" => "Bradford, University of"),
            array("course_name" => "Politics, Philosophy And Law LLB", "university" => "Leuphana University"),
            array("course_name" => "LLM In International Commercial Law", "university" => "UAM University"),
            array("course_name" => "BA Management And Leadership With European Study", "university" => "Polytechnic di Torino"),
            array("course_name" => "Philosophy, Politics And Economics", "university" => "Trinity College Carmarthen"),
            array("course_name" => "LL.B Law", "university" => "Clark Atlanta University"),
            array("course_name" => "European Law (Maitrise)", "university" => "Providence College"),
            array("course_name" => "LLB (European) Law", "university" => "City of Sunderland College"),
            array("course_name" => "BA Economics", "university" => "University College Birmingham"),
            array("course_name" => "Anthropology And Law", "university" => "Xidian University"),
            array("course_name" => "LLM In Banking And Finance", "university" => "Cardiff University"),
            array("course_name" => "BSc Philosophy, Logic And Scientific Method", "university" => "ESCP Europe (London)"),
            array("course_name" => "LLM Tax Law", "university" => "UAM University"),
            array("course_name" => "Law (3yr LLB)", "university" => "Koc University"),
            array("course_name" => "Law And Business", "university" => "Brighton College of Technology"),
            array("course_name" => "Law And European Law (Qualifying Year Abroad In English)", "university" => "Saint Mary's College of Meycauayan"),
            array("course_name" => "Law (3 Years)", "university" => "Jacksonville University"),
            array("course_name" => "Law (M100)", "university" => "Hofstra University"),
            array("course_name" => "Law And Business Studies", "university" => "Beijing Institute of Technology"),
        );


        foreach ($courses as $course) {
            Course::create($course);
        }
    }

}
